# Linux: ~/.config/lazygit/config.yml
# MacOS: ~/Library/Application Support/lazygit/config.yml
# Windows: %APPDATA%\lazygit\config.yml

os:
  edit: 'code -rg {{filename}}'
  editAtLine: '{{editor}} --goto {{filename}}:{{line}}'
  
